### ISSUE TITLE
Grant mcatpeery permission to deposit in CORE on behalf of plotznik

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/humanities-commons#51]
Support team member: Larissa
Date first reported: 6-1-2022 
Site: hcommons.org 
Area: CORE

Grant [mcatpeery](https://hcommons.org/members/mcatpeery/) permission to deposit in CORE on behalf of [plotznik](https://hcommons.org/members/plotznik/)

Asked as part of HC private message with Larissa

**Comment by mikethicke** [comment]
mcatpeery should be able to deposit on behalf of others. They should see a radio button on the deposit page that allows them to deposit as a different user. Note: it's not specific to a particular user.

**Comment by babaklar** [comment]
Emailed plotznik to inform him of update.
