### ISSUE TITLE
Email Survey Email at 11 AM EDT on 3/1

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/humanities-commons#56]
Survey email subject and text can be found at: https://docs.google.com/document/d/1jnqq6u1THiP55m5Ii-hUS24oZ-DVn-fbrDdTnneFDtI/edit?usp=sharing

**Comment by babaklar** [comment]
HTML and TXT files of the email in the template are in the attached zip.

[User survey 2.zip](https://github.com/MESH-Research/humanities-commons/files/10852843/User.survey.2.zip)

**Comment by babaklar** [comment]
UPDATED files attached here:

[https://app.zenhub.com/files/62333771/4dc18caa-f4a4-4f2d-abaa-e4b19db3932e/download](https://app.zenhub.com/files/62333771/4dc18caa-f4a4-4f2d-abaa-e4b19db3932e/download)
